server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Madhura@58
    driver-class-name: com.mysql.cj.jsbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true